// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-publications.ts
import { createClient } from "npm:@supabase/supabase-js@^2.52.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var list_publications_default = defineTool({
  name: "list_publications",
  title: "List publications",
  description: "List the most recent published publications available on the BIC platform (title, category, price, publication date).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of publications to return (default 10, max 50)."),
    category: z.string().optional().describe("Optional category filter (case-insensitive substring match).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let query = supabase.from("publications").select("id,title,category,price_usd,published_at,status").eq("status", "published").order("published_at", { ascending: false }).limit(limit ?? 10);
    if (category) query = query.ilike("category", `%${category}%`);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { publications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-articles.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.52.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_articles_default = defineTool2({
  name: "list_articles",
  title: "List articles",
  description: "List the most recent published articles/blog posts from the BIC platform (title, slug, theme, published date).",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Maximum number of articles to return (default 10, max 50)."),
    theme: z2.string().optional().describe("Optional theme filter (case-insensitive substring).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, theme }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let query = supabase.from("articles").select("id,title,slug,theme,published_at,status").eq("status", "published").order("published_at", { ascending: false }).limit(limit ?? 10);
    if (theme) query = query.ilike("theme", `%${theme}%`);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/verify-document.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.52.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var verify_document_default = defineTool3({
  name: "verify_document",
  title: "Verify a BIC document",
  description: "Verify the authenticity of a BIC-issued document (certificate, permit, mutation, etc.) by its verification code. Returns non-sensitive validity metadata only.",
  inputSchema: {
    code: z3.string().min(3).describe("The verification code printed on the document (e.g. BIC-CERT-XXXX).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ code }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.rpc("verify_document_public", {
      _verification_code: code.trim()
    });
    if (error) {
      return {
        content: [{ type: "text", text: `Verification unavailable: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? { valid: false }, null, 2) }],
      structuredContent: { result: data ?? { valid: false } }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "bic-mcp",
  title: "BIC RDC MCP",
  version: "0.1.0",
  instructions: "Read-only tools for the BIC (Bureau d'Intelligence Cadastrale RDC) platform: list published publications and articles, and verify the authenticity of a BIC-issued document by its verification code.",
  tools: [list_publications_default, list_articles_default, verify_document_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
