
-- Insérer la parcelle 321345 dans cadastral_parcels avec les bonnes valeurs
INSERT INTO cadastral_parcels (
  parcel_number,
  parcel_type,
  location,
  property_title_type,
  current_owner_name,
  current_owner_legal_status,
  current_owner_since,
  area_sqm,
  gps_coordinates,
  province,
  ville,
  commune,
  quartier,
  avenue,
  construction_type,
  construction_nature,
  declared_usage,
  lease_type,
  property_title_document_url,
  owner_document_url,
  title_reference_number,
  parcel_sides
) VALUES (
  '321345',
  'SU',
  'Goma, Quartier Les Volcans, Avenue du lac',
  'Certificat de location',
  'Mugabe  Magambo Jean',
  'Personne physique',
  '2024-11-15',
  100,
  '[{"borne":"Borne 1","lat":-1.703465,"lng":29.293684},{"borne":"Borne 2","lat":-1.703912,"lng":29.293445},{"borne":"Borne 3","lat":-1.703556,"lng":29.293769},{"borne":"Borne 4","lat":-1.703524,"lng":29.293409}]'::jsonb,
  'Nord-Kivu',
  'Goma',
  'Goma',
  'Les Volcans',
  'Avenue du lac',
  'Résidentielle',
  'Durable',
  'Résidentiel',
  'renewal',
  'https://vqrcggcqgnkanngqhcga.supabase.co/storage/v1/object/public/cadastral-documents/title-documents/zkhy19utiu.jpg',
  'https://vqrcggcqgnkanngqhcga.supabase.co/storage/v1/object/public/cadastral-documents/owner-documents/05go93rag92m.jpg',
  'Gfy4667',
  '[{"length":10,"name":"Côté Nord"},{"length":10,"name":"Côté Sud"},{"length":10,"name":"Côté Est"},{"length":10,"name":"Côté Ouest"}]'::jsonb
)
ON CONFLICT (parcel_number) DO NOTHING;
