// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqrcggcqgnkanngqhcga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxcmNnZ2NxZ25rYW5uZ3FoY2dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDA3MTcsImV4cCI6MjA2OTI3NjcxN30.PP_49nOFnaC8aDf5IG3J0CAaPJi6zM_wppLy2qJG6BQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});